### ISSUE TITLE
Transferir las opciones de package.json a auto-deploy.json

### ISSUE THREAD

**Issue by diegoefe** [codenautas/auto-deploy#3]
Esto implicaría:
1 no tener que definirlas en los programas cliente
2 sólo tener que agregar la línea en "scripts": "auto-deploy": "node auto-deploy-runner.js"
3 tener que re-definir (de ser necesario) las opciones "custom" para un proyecto determinado de la vieja manera (con la sección "auto-deploy" en project/package.json

**Comment by emilioplatzer** [comment]
Del punto 2, me parece que se podría evaluar en vez de eso en el script "start" poner:
`node auto-deploy-runnerj.js -- server.js` o similar. 

O sea si antes uno tenía en "start" `node programa.js parametro1 parametro2` ahora pondría:
`node auto-deploy-runner.js -- programa.js parametro1 parametro2`. El "--" está como separador de parámetros para uso futuro (o sea para poderle pasar opciones al auto-deploy.

**Comment by diegoefe** [comment]
Creo que ya estamos
