### ISSUE TITLE
Cambiar la manera de invocar/instalar el middleware

### ISSUE THREAD

**Issue by diegoefe** [codenautas/auto-deploy#4]
Remover el método install()

**Comment by emilioplatzer** [comment]
Al invocar a la función que crea el middleware se puede verificare que el programa esté invocado (o sea tenga como padre) el auto-deploy-runner.js. En caso de no tenerlo lanzar una excepción que diga "this program must be called with auto-deploy-runner.js"

**Comment by diegoefe** [comment]
Buena idea

**Comment by diegoefe** [comment]
Hecho
